services:
  - type: web
    name: baccarat-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application --bind 0.0.0.0:10000
    envVars:
      - key: PORT
        value: 10000
